---
kind: pipeline
type: kubernetes
name: Aton

steps:
  - name: linter
    image: golang:1.15.6
    commands:
      - apt-get update
      - apt-get install -y libdlib-dev libblas-dev liblapack-dev libjpeg62-turbo-dev
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
      - go get ./...
      - make lint

  - name: unit-tests
    image: golang:1.15.6
    commands:
      - make test-unit

  - name: integration-tests
    image: golang:1.15.6
    depends_on:
      - linter
      - unit-tests
    commands:
      - apt-get update
      - apt-get install -y libdlib-dev libblas-dev liblapack-dev libjpeg62-turbo-dev
      - make test-integration
    when:
      branch:
        include:
          - master

  - name: node-tests
    image: golang:1.15.6
    depends_on:
      - linter
      - unit-tests
    commands:
      - apt-get update
      - apt-get install -y libdlib-dev libblas-dev liblapack-dev libjpeg62-turbo-dev
      - make test-node
    when:
      branch:
        include:
          - master

  - name: racy-tests
    image: golang:1.15.6
    depends_on:
      - linter
      - unit-tests
    commands:
      - apt-get update
      - apt-get install -y libdlib-dev libblas-dev liblapack-dev libjpeg62-turbo-dev
      - make test-racy
    when:
      branch:
        include:
          - master

  - name: e2e-tests
    image: golang:1.15.6
    depends_on:
      - linter
      - unit-tests
    commands:
      - apt-get update
      - apt-get install -y libdlib-dev libblas-dev liblapack-dev libjpeg62-turbo-dev
      - make test-e2e
    when:
      branch:
        include:
          - master

  - name: notify
    image: drillster/drone-email
    depends_on:
      - integration-tests
      - node-tests
      - racy-tests
      - e2e-tests
    when:
      status: [ success, failure ]
    environment:
      PLUGIN_FROM:
        from_secret: email_username
      EMAIL_HOST:
        from_secret: email_host
      EMAIL_PORT:
        from_secret: email_port
      EMAIL_USERNAME:
        from_secret: email_username
      EMAIL_PASSWORD:
        from_secret: email_password