language: go
go:
  - 1.15.5
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libdlib-dev libblas-dev liblapack-dev libjpeg-dev
jobs:
  include:
    - name: "Linter"
      stage: linter
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
        - go get ./...
        - make lint

    - name: "Unit tests"
      stage: unit-test
      script: make test-unit

    - name: "Integration tests"
      stage: integration-test
      branches:
        only:
          - master
      script: make test-integration

    - name: "Detector tests"
      stage: integration-test
      branches:
        only:
          - master
      before_script: make docker-test
      script: make test-detector
      services: docker

    - name: "Racy tests"
      stage: integration-test
      branches:
        only:
          - master
      script: make test-racy

    - name: "End to End tests"
      stage: integration-test
      branches:
        only:
          - master
      script: make test-racy

stages:
  - linter
  - unit-test
  - integration-test