// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.1
// source: internal/detector/proto/detector.proto

package detector

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LoadCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []string `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Image      []byte   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *LoadCategoriesRequest) Reset() {
	*x = LoadCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_detector_proto_detector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCategoriesRequest) ProtoMessage() {}

func (x *LoadCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_detector_proto_detector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCategoriesRequest.ProtoReflect.Descriptor instead.
func (*LoadCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_internal_detector_proto_detector_proto_rawDescGZIP(), []int{0}
}

func (x *LoadCategoriesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *LoadCategoriesRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type LoadCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LoadCategoriesResponse) Reset() {
	*x = LoadCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_detector_proto_detector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCategoriesResponse) ProtoMessage() {}

func (x *LoadCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_detector_proto_detector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCategoriesResponse.ProtoReflect.Descriptor instead.
func (*LoadCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_internal_detector_proto_detector_proto_rawDescGZIP(), []int{1}
}

func (x *LoadCategoriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadCategoriesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RecognizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     []byte               `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_detector_proto_detector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_detector_proto_detector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_internal_detector_proto_detector_proto_rawDescGZIP(), []int{2}
}

func (x *RecognizeRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *RecognizeRequest) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RecognizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names        []string             `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Success      bool                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message      string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RecognizedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=recognized_at,json=recognizedAt,proto3" json:"recognized_at,omitempty"`
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_detector_proto_detector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_detector_proto_detector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_internal_detector_proto_detector_proto_rawDescGZIP(), []int{3}
}

func (x *RecognizeResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *RecognizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecognizeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecognizeResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RecognizeResponse) GetRecognizedAt() *timestamp.Timestamp {
	if x != nil {
		return x.RecognizedAt
	}
	return nil
}

var File_internal_detector_proto_detector_proto protoreflect.FileDescriptor

var file_internal_detector_proto_detector_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x15, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x22, 0x4c, 0x0a, 0x16, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x63, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xd9, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x3f, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x64, 0x41,
	0x74, 0x32, 0xa9, 0x01, 0x0a, 0x08, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x53,
	0x0a, 0x0e, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x1f, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65,
	0x12, 0x1a, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x67, 0x6e, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x6f, 0x79,
	0x6c, 0x70, 0x2f, 0x61, 0x74, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_detector_proto_detector_proto_rawDescOnce sync.Once
	file_internal_detector_proto_detector_proto_rawDescData = file_internal_detector_proto_detector_proto_rawDesc
)

func file_internal_detector_proto_detector_proto_rawDescGZIP() []byte {
	file_internal_detector_proto_detector_proto_rawDescOnce.Do(func() {
		file_internal_detector_proto_detector_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_detector_proto_detector_proto_rawDescData)
	})
	return file_internal_detector_proto_detector_proto_rawDescData
}

var file_internal_detector_proto_detector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_detector_proto_detector_proto_goTypes = []interface{}{
	(*LoadCategoriesRequest)(nil),  // 0: detector.LoadCategoriesRequest
	(*LoadCategoriesResponse)(nil), // 1: detector.LoadCategoriesResponse
	(*RecognizeRequest)(nil),       // 2: detector.RecognizeRequest
	(*RecognizeResponse)(nil),      // 3: detector.RecognizeResponse
	(*timestamp.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_internal_detector_proto_detector_proto_depIdxs = []int32{
	4, // 0: detector.RecognizeRequest.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: detector.RecognizeResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: detector.RecognizeResponse.recognized_at:type_name -> google.protobuf.Timestamp
	0, // 3: detector.Detector.LoadCategories:input_type -> detector.LoadCategoriesRequest
	2, // 4: detector.Detector.Recognize:input_type -> detector.RecognizeRequest
	1, // 5: detector.Detector.LoadCategories:output_type -> detector.LoadCategoriesResponse
	3, // 6: detector.Detector.Recognize:output_type -> detector.RecognizeResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_detector_proto_detector_proto_init() }
func file_internal_detector_proto_detector_proto_init() {
	if File_internal_detector_proto_detector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_detector_proto_detector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_detector_proto_detector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_detector_proto_detector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_detector_proto_detector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_detector_proto_detector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_detector_proto_detector_proto_goTypes,
		DependencyIndexes: file_internal_detector_proto_detector_proto_depIdxs,
		MessageInfos:      file_internal_detector_proto_detector_proto_msgTypes,
	}.Build()
	File_internal_detector_proto_detector_proto = out.File
	file_internal_detector_proto_detector_proto_rawDesc = nil
	file_internal_detector_proto_detector_proto_goTypes = nil
	file_internal_detector_proto_detector_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DetectorClient is the client API for Detector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DetectorClient interface {
	LoadCategories(ctx context.Context, in *LoadCategoriesRequest, opts ...grpc.CallOption) (*LoadCategoriesResponse, error)
	Recognize(ctx context.Context, opts ...grpc.CallOption) (Detector_RecognizeClient, error)
}

type detectorClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectorClient(cc grpc.ClientConnInterface) DetectorClient {
	return &detectorClient{cc}
}

func (c *detectorClient) LoadCategories(ctx context.Context, in *LoadCategoriesRequest, opts ...grpc.CallOption) (*LoadCategoriesResponse, error) {
	out := new(LoadCategoriesResponse)
	err := c.cc.Invoke(ctx, "/detector.Detector/LoadCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *detectorClient) Recognize(ctx context.Context, opts ...grpc.CallOption) (Detector_RecognizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Detector_serviceDesc.Streams[0], "/detector.Detector/Recognize", opts...)
	if err != nil {
		return nil, err
	}
	x := &detectorRecognizeClient{stream}
	return x, nil
}

type Detector_RecognizeClient interface {
	Send(*RecognizeRequest) error
	Recv() (*RecognizeResponse, error)
	grpc.ClientStream
}

type detectorRecognizeClient struct {
	grpc.ClientStream
}

func (x *detectorRecognizeClient) Send(m *RecognizeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *detectorRecognizeClient) Recv() (*RecognizeResponse, error) {
	m := new(RecognizeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DetectorServer is the server API for Detector service.
type DetectorServer interface {
	LoadCategories(context.Context, *LoadCategoriesRequest) (*LoadCategoriesResponse, error)
	Recognize(Detector_RecognizeServer) error
}

// UnimplementedDetectorServer can be embedded to have forward compatible implementations.
type UnimplementedDetectorServer struct {
}

func (*UnimplementedDetectorServer) LoadCategories(context.Context, *LoadCategoriesRequest) (*LoadCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadCategories not implemented")
}
func (*UnimplementedDetectorServer) Recognize(Detector_RecognizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Recognize not implemented")
}

func RegisterDetectorServer(s *grpc.Server, srv DetectorServer) {
	s.RegisterService(&_Detector_serviceDesc, srv)
}

func _Detector_LoadCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServer).LoadCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/detector.Detector/LoadCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServer).LoadCategories(ctx, req.(*LoadCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Detector_Recognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DetectorServer).Recognize(&detectorRecognizeServer{stream})
}

type Detector_RecognizeServer interface {
	Send(*RecognizeResponse) error
	Recv() (*RecognizeRequest, error)
	grpc.ServerStream
}

type detectorRecognizeServer struct {
	grpc.ServerStream
}

func (x *detectorRecognizeServer) Send(m *RecognizeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *detectorRecognizeServer) Recv() (*RecognizeRequest, error) {
	m := new(RecognizeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Detector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "detector.Detector",
	HandlerType: (*DetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadCategories",
			Handler:    _Detector_LoadCategories_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Recognize",
			Handler:       _Detector_Recognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/detector/proto/detector.proto",
}
